FROM maven:3.9.8-eclipse-temurin-17

USER root
RUN mkdir /app
WORKDIR /app

COPY pom.xml ./
RUN mvn dependency:go-offline
COPY src ./src

ENV ALLURE_RESULTS=/app/allure-results

ENTRYPOINT ["sh", "-c", "\
  mvn clean test \
  -Dbrowser=${BROWSER} \
  -Dbrowser_version=${BROWSER_VERSION} \
  -Dbase_url=${BASE_URL} \
  -Dremote=${REMOTE} \
  -Dselenoid_url=${SELENOID_URL} \
  -Denable_video=${ENABLE_VIDEO} \
  -Denable_vnc=${ENABLE_VNC} \
  -Dallure.results.directory=${ALLURE_RESULTS}"]
